services:
    backend:
        build: ./backend
        container_name: backend_container
        ports:
            - "4000:4000"
        volumes:
            - ./backend:/app
            - /app/node_modules
        env_file:
            - ./backend/.env

    frontend:
        build: ./frontend
        container_name: frontend_container
        ports:
            - "3000:3000"
        depends_on:
            - backend
        stdin_open: true
        tty: true
        volumes:
            - ./frontend:/app
            - /app/node_modules
