name: Docker Image CD

on:
    workflow_run:
        workflows: ["Docker Image CI"]
        types:
            - completed

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Pull docker image
              run: sudo docker pull gayan65/parkez-backend:latest
            - name: Delete old docker container
              run: sudo docker rm -f parkez-backend-container || true
            - name: Run docker container
              shell: bash
              run: |
                  sudo docker run -d -p 4000:4000 --name parkez-backend-container \
                  -e DB_URL="${{ secrets.DB_URL }}" \
                  -e PORT="${{ secrets.PORT }}" \
                  -e PASS="${{ secrets.PASS }}" \
                  -e SALT="${{ secrets.SALT }}" \
                  -e SECRET="${{ secrets.SECRET }}" \
                  gayan65/parkez-backend

            - name: Pull frontend docker image
              run: sudo docker pull gayan65/parkez-frontend:latest
            - name: Delete old frontend docker container
              run: sudo docker rm -f parkez-frontend-container || true
            - name: Run frontend docker container
              shell: bash
              run: |
                  sudo docker run -d -p 3000:80 --name parkez-frontend-container \
                  gayan65/parkez-frontend
